config/routes.rb
Rails.application.routes.draw do

  resources :iframe_games
  resources :videos
get 'budgets/before_new'

resources :budgets do
  collection do
    put :update_attribute_on_the_spot
    get :get_attribute_on_the_spot
  end
end

get 'pages/home'
get 'pages/about'
get 'pages/front'
get 'pages/profile'
get 'pages/store'
get 'pages/calculator'

devise_for :users, :controllers => { registrations: 'registrations' }, :path_names => {:sign_up => "register"}

  root 'pages#front'

 

end

app/models/budget.rb
class Budget < ActiveRecord::Base
	belongs_to :user

	validates :title, presence: true,
			:length => { :minimum => 2, :maximum => 24, :message => "has invalid length"}




end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  
  can_edit_on_the_spot

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    #number f columns excluding created at columns, id and foreign key
    @num_columns = (Budget.column_names.length - 5)
    @column_names_array = Budget.columns.map { |column| column.name }
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end 

  def before_new
    #@chosen_fields = (params[:chosen_fields])
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:title, :money_in, :week, :savings, :bills, :lunches, :phone, :travel, :clothing, :activities, :entertainment, :emergency_fund, :chosen_fields)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper

	def bleh
		arr = [[3,4],[5,6]]
		arr.each do |(a,b)|
		  puts "#{a} #{b}"
		  puts a
		end
	end

	def comebacktonameme

		@column_names_array.delete("title")
		@column_names_array.delete("updated_at")
		@column_names_array.delete("created_at")
		@column_names_array.delete("user_id")
		@column_names_array.delete("id")
		return @column_names_array
	end



end

app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% @budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="fields" style="border: 1px solid black; display: none;">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, id: "ttieee" %>
  </div>
  <div class="field">
    <%= f.label :money_in %><br>
    <%= f.text_field :money_in %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :savings %><br>
    <%= f.text_field :savings %>
  </div>
  <div class="field">
    <%= f.label :bills %><br>
    <%= f.text_field :bills %>
  </div>
  <div class="field">
    <%= f.label :lunches %><br>
    <%= f.text_field :lunches %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :travel %><br>
    <%= f.text_field :travel %>
  </div>
  <div class="field">
    <%= f.label :clothing %><br>
    <%= f.text_field :clothing %>
  </div>
  <div class="field">
    <%= f.label :activities %><br>
    <%= f.text_field :activities %>
  </div>
  <div class="field">
    <%= f.label :entertainment %><br>
    <%= f.text_field :entertainment %>
  </div>
  <div class="field">
    <%= f.label :emergency_fund %><br>
    <%= f.text_field :emergency_fund %>
  </div>
</div>
  <div class="actions">
    <%= image_submit_tag("confirm.png", class: "img img-responsive col-md-2 col-md-push-5 hidden", id: "submitBudgetBtn") %>
  </div>
<% end %>

app/views/budgets/before_new.html.erb
<% stylesheet_link_tag   'dragula'  %>
<%= stylesheet_link_tag   'before_new'  %>

<!-- Ruby variables -->
<% chosen_fields = "none" %>

<button href="#" class="btn stickyBtn" onclick="showDragAndDrop();" data-toggle="tooltip" title="Hide or Show the Drag & Drop box"><i id="stickyBtnIcon" class=" fa fa-chevron-down fa-5x" ></i></button>

<div class= "examples" style="margin-left:10px;">
	<button type="button" class="btn helpBtn" data-toggle="modal" data-target="#helpModal">
		Help <span class="glyphicon glyphicon-question-sign"></span>
	</button>
	<div class='parent'>
		<h1 style="text-align: center;">What categories are you <u>Budgeting</u> for this week:</h1>
		<ul id='right-defaults' class='col-md-10 col-md-push-1' style="border: 2px dashed #7b69eb; min-height:200px; padding: 10px;"> </ul>
		<div class='wrapper col-md-12'>
			<ul id='left-defaults' class='col-md-12' style=" min-height: 200px;">
			    <li class="col-md-4">Savings <%= image_tag "savings", class: "img img-responsive col-md-3" %> </li>
			    <li class="col-md-4">Bills <%= image_tag "bills", class: "img img-responsive col-md-3" %></li>
			    <li class="col-md-4">Lunches <%= image_tag "lunches", class: "img img-responsive col-md-3" %></li>
			    <li class="col-md-4">Phone <%= image_tag "phone", class: "img img-responsive col-md-3" %></li>
			    <li class="col-md-4">Travel <%= image_tag "travel", class: "img img-responsive col-md-3" %></li>
			    <li class="col-md-4">Clothing <%= image_tag "clothing", class: "img img-responsive col-md-3" %></li>
				<li class="col-md-4">Activities <%= image_tag "activities", class: "img img-responsive col-md-3" %></li>
			    <li class="col-md-4">Entertainment <%= image_tag "entertainment", class: "img img-responsive col-md-3" %></li>
			    <li class="col-md-4" style="font-size: 2em; line-height: 23px;">Emergency fund <%= image_tag "emergency", class: "img img-responsive col-md-3" %></li>
			    <div class="col-md-12"><li class="col-md-6 col-md-push-3 whiteFont font600 marginTop20">Make up my own <br><%= image_tag "idea", class: "img img-responsive col-md-2 col-md-push-5 centered" %></li></div>
			</ul>
		</div>  
	</div>
	<button class="btn btn-lg greenBG whiteFont" onclick="submitClicked();" style="margin-top: 50px; margin-right: 10px; float: right; margin-bottom: 5px;"> I'm ready to make my budget </button>
  </div>
<!-- list -->
<div id="list">
	<div class="row" style="padding-bottom: 20px; padding-top: 50px;">
		<div class="col-xs-5" style="background-color: #7b69eb; text-align: center;">
			<h2 class="">This budget:</h2>
			<!-- alert shown to user if no items selected -->
			<div class="alert alert-warning listIsEmpty" >
			  <strong> <h3>It looks like you forgot to choose some items to make your budget with</h3></strong>
			  <div id="emptyListMessage" class="row">
			  	<h4>Would you like to to do that now?</h4>
			  	<button type="button" class="btn btn-success col-md-5 col-md-push-1" 
			  			style="margin-right: 5px;" onclick="showDragAndDrop()">Yes</button>
			  	<button type="button" class="btn btn-danger col-md-5 col-md-push-1" data-toggle="modal" data-target=".bs-example-modal-lg">No I don't want to make a budget</button>
			  </div>
			</div>
		</div>
	</div>
	<div class="container" id="prettyList" style="padding-bottom: 50px;"></div>
	<div id="changeSomethingBtn" onclick="showDragAndDrop()">Wait! I want to Change Something</div>
	<%= link_to "continue", new_budget_path(:chosen_fields => chosen_fields), id: "submitBtn", class: "bounce" %>
</div>

<!-- Modal -->
<div id="helpModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Watch How to Create a Budget  -  ( Click to restart it )</h4>
      </div>
      <div class="modal-body">
       	<center><%= image_tag("help_before_new", class: "help_before_new_img",
        :onclick => 'this.src=this.src') %> </center>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default redFont" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag   'before_new'  %>
<%= javascript_include_tag   'dragula'  %>
<%= javascript_include_tag   'example.min'  %>

<!-- the aim is to be able to pass differtnt path/routes to the variables below and dynamically link to them using the partial -->
<% errorMessage = "Are you sure you want to leave this page?"  %>
<% yesPath1 = root_path  %> <!-- not working as inteded yet -->
<% yesPath2 = "Yes I want to got to Y"  %> <!-- not working as inteded yet -->


 <!-- render the Error partial and pass it parameters (column name and its value) -->
 <%= render 'shared/errorModal',  :val1 =>  errorMessage,  :val2 =>  yesPath1,  :val3 =>  yesPath2 %>






app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Budgets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Money in</th>
      <th>Week</th>
      <th>Savings</th>
      <th>Bills</th>
      <th>Lunches</th>
      <th>Phone</th>
      <th>Travel</th>
      <th>Clothing</th>
      <th>Activities</th>
      <th>Entertainment</th>
      <th>Emergency fund</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.title %></td>
        <td><%= budget.money_in %></td>
        <td><%= budget.week %></td>
        <td><%= budget.savings %></td>
        <td><%= budget.bills %></td>
        <td><%= budget.lunches %></td>
        <td><%= budget.phone %></td>
        <td><%= budget.travel %></td>
        <td><%= budget.clothing %></td>
        <td><%= budget.activities %></td>
        <td><%= budget.entertainment %></td>
        <td><%= budget.emergency_fund %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<!-- tidy this whole file when finished -->
<%= stylesheet_link_tag "new" %>
<%= javascript_include_tag "http://www.gerardolarios.com/plugins-and-tools/jqmeter/js/jqmeter.min.js" %>
<h1 id="progressbarMoney_in"></h1>
<div id="myProgress" class="row">
	<div id="myBar" class="col-md-1" style="background-color: #019875;"> </div>
	<div id="myBar2" class="col-md-1"> </div>
  <!-- <div id="barEnd" class="col-md-1" style="background-color: #EF4836; float: right; padding: 20px;"> -->
	<!-- <div class="col-md-1 halfCircleRight"></div> -->

	<!-- <div id="barEndText" class="col-md-10"></div>
  </div> -->
  <div class="circlediv" style="max-height: 100%;">
  	<div id="circledivText" class="col-md-11 col-md-push-1"></div>
  </div>
</div>
<div id="wheelContainer">
<h1 id="title">Name of Budget</h1>
<div class="spinWheel cursor" >
    <div class="first"><input id="currentField1" type="text" class="rq-form-element"><i></i></div>
    <div class="second"><input id="currentField3" type="text" ></div>
    <div class="third"><input id="currentField2" type="text" ></div>
</div>
</div>
<%# button_tag "Next", onclick: 'spinWheel();'%>

<!-- get the fields that the user wishes to populate, split the recieved string up and left with array -->
<% chosen_fields = params['chosen_fields'] %>
<div class="recievedParams" style="margin-top: 100px; display: none;"><%= chosen_fields %></div>

<!-- count number of items revieved -->
<div class="hidden numParams">
	<% if chosen_fields %>
		<%= chosen_fields.split.size %>
	<% end %>
</div>

<%= javascript_include_tag "new" %>

<%= render 'form' %>

<%# link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>


<!-- excludes nil columns (will exclude created_and other defaults too ) And excludes money_in, week  --> 
<center>
  <%= pie_chart @budget.dup.attributes.keep_if{|k,v| !v.nil? && !(k ==  "money_in" || k ==  "week" ) }, 
        width: "800px",
        height: "400px",
        legend: "bottom" %>
</center>

<style>
  blockquote{
    border-left:none
}
.quote-badge{
    background-color: rgba(0, 0, 0, 0.2);   
}
.quote-box{
  overflow: hidden;
  border-radius: 17px;
  background-color: #4ADFCC;
  margin-top: 25px;
  margin-left: 60px;
  color:white;
  box-shadow: 2px 2px 2px 2px #E0E0E0;
  padding-bottom: 25px;
  max-height: 100%;
}

.quotation-mark{
  text-align: center;
    height: 150px;
    font-weight: bold;
    font-size:40px;
    color:white;
    font-family: "Times New Roman", Georgia, Serif;
}

.quote-text{
    margin-top: -70px;
    padding-bottom: 30px;
    font-size: 40px;
    text-align: center;
}

.on_the_spot_editing form{
  font-size: 0.3em;
  color: black;
  background-color: red;
}
.on_the_spot_editing button{
  visibility: hidden;
  display:none;
}

/* items with no value */
.itsBlank{background-color: #ff6060; opacity: 0.5;}
.itsBlank:hover{background-color: #46c4b4; opacity: 0.7;}
</style>


<% @num_columns.times do |budget| %>
<% col_name = comebacktonameme[budget] %>

<% col_name %>
<% otherval = @budget.public_send(col_name) if @budget.respond_to? col_name  %>

<!-- check which ones are not filled in to give it a different css class -->
<%# is_blank =  otherval < 1 ? 'itsBlank' :  'notBlank'  %> 

  <!-- render the partial and pass it parameters (column name and its value) -->
  <%= render 'shared/budget_item',  :val1 =>  col_name, :val2 =>  otherval, :val3 =>  "is_blank" %>


  <% budget %> 

<% end %>




<% link_to 'Edit all at the same time', edit_budget_path(@budget) %> 
<% link_to 'Back', budgets_path %>




<script>
  $(".on_the_spot_editing").focus(function(){
    //$(".on_the_spot_editing span").css("color", "red");
      alert("ddddddd")
  })


  function fieldChanged(){

  }

  $('span').change(function(e) {
    $(this).closest( "blockquote" ).removeClass( "itsBlank" );
});


</script>