config/routes.rb
Rails.application.routes.draw do

  resources :iframe_games
  resources :videos
get 'budgets/before_new'

resources :budgets do
  collection do
    put :update_attribute_on_the_spot
    get :get_attribute_on_the_spot
  end
end

get 'pages/home'
get 'pages/about'
get 'pages/front'
get 'pages/profile'
get 'pages/store'
get 'pages/calculator'

devise_for :users, :controllers => { registrations: 'registrations' }, :path_names => {:sign_up => "register"}

  root 'pages#front'

 

end

app/views/pages/_header.html.erb
      <div id="navigation" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="color: #7b69eb;" href="/"><b>My Money Counts</b></a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/" class="smothscroll">About the app</a></li>
              <% if !user_signed_in? %>
                    <li> <%= link_to('Login', new_user_session_path)  %> </li>
                    <li> <%= link_to('Sign up', new_user_registration_path)  %> </li>    
              <% else %>
                     <li><a href="/pages/profile">My Profile</a></li>
                    <!-- <li><a href="/pages/profile">My Budgets</a></li> -->
                    <li><a href="/budgets/before_new">Create a Budget now</a></li>    
                </ul>
                <ul class="nav navbar-nav" style="float: right;">
                    <li><a href="/pages/store">App Store</a></li> 
                    <li><%= link_to "Videos", videos_path %> </li>
                    <li><%= link_to('Logout', destroy_user_session_path) %></li>   
                </ul>
              <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>



<!-- <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">My Money Counts</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
                <ul class="dropdown-menu">

                  
                  </li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><%= link_to "All Budgets", budgets_path %></li>
              <li><%= link_to "Create Budget", budgets_before_new_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav> 

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<br>
<br>
<br>
<br>
<br>
<br>
<p> heyyyyyyyy down here </p>

app/views/pages/calculator.html.erb
<style type="text/css">
/*structure around the calc*/
	.typeOfCalcBtn{
		 height: 100px;
		 color: white;
		 text-align: center;
		 border: 3px solid white;
		 border-radius: 15px 15px 0px 0px;
	}
	.typeOfCalcBtnArrow{
		font-size: 4em;
		text-align: center;
		margin-top: -10px;
	}
	.calculatorMain{
		border: 3px solid white;
		border-radius: 10px;
		min-height: 300px;
		padding-bottom: 20px;
	}
/* ./structure around the calc*/

/*calculator*/
	.calculator {
	    /*width: 170px;*/
	    background-color: #484848;
	    padding: 20px;
	    margin-top: 50px;
	    border-radius: 10px;
	}

	.result {
	    width: 100%;
	    height: 35px;
	    background-color: #cddecc;
	    border-radius: 5px;
	    margin-bottom: 15px;
	    text-align: right;
	    line-height: 34px;
	    font-family: digital;
	    padding: 0px 5px 0px 5px;
	    font-size: 25px;
	    overflow: hidden;
	    box-shadow: inset 0 0px 3px;
	    text-align: center;
    	font-weight: 800;
    	color: #7b69eb;
	}

	.key {
	    /*width: 35px;*/
	    width: 20%;
	    background-color: #eeeeee;
	    display: inline-block;
	    margin: 3px 0px 8px 3px;
	    vertical-align: bottom;
	    text-align: center;
	    padding: 15px 0px 5px 0px;
	    font-weight: bold;
	    border-radius: 4px;
	    cursor: pointer;
	    box-shadow: 0 3px 0 #a1a1a1, 0 2px 5px rgba(0, 0, 0, .75);
	}

	.equal-key {
	    width: 61%;
	    background-color: #4a9840;
	    color: white;
	}

	.clear-key {
	    background-color: #bb1c09;
	    color: white;
	}

	.right-key{
		width: 25%;
	    margin-left: 13%;
	}

	.key:active {
	    background-color: #a1a1a1;
	    box-shadow: 0 5px #666;
	    transform: translateY(4px);
	}
	/*moneyCalc*/
	.key-money{
		/*overwrite few things for money-key (from .key)*/
		padding: 0px 0px 0px 0px;
		box-shadow: 0 3px 0 #eeeeee, 0 2px 5px rgba(0, 0, 0, .75);
	}
	#calculator_money span img{height: 100%;}
	#calculator_money span.key{
		height: 50px;
		max-height: 50px;
	}

/* ./ calculator*/
</style>
<!-- change this minus business! -->
<div style="margin-top: -50px;">
	<div class="col-md-6 typeOfCalcBtn numberCalcBtn" style="background-color: #78CBC3;">
		<h1>Number calculator</h1>
	</div>
	<div class="col-md-6 typeOfCalcBtn moneyCalcBtn" style="background-color: #7b69eb;">
		<h1>Money calculator</h1>
	</div>	
	<!-- arrows that indicate which calculator is active -->
	<div id="arrow1" class="col-md-6 typeOfCalcBtnArrow" style="color: #78CBC3; visibility: hidden;">
		<i class="fa fa-caret-down"></i>
	</div>
	<div id="arrow2" class="col-md-6 typeOfCalcBtnArrow" style="color: #7b69eb;">
		<i class="fa fa-caret-down"></i>
	</div>	

	<div class="col-md-12 calculatorMain" style="background-color: #7b69eb;">
		<!-- number calculator -->
		 <div id="calculator_number" class="col-md-6 col-md-push-3 calculator hidden">
	        <div id="" class="result"></div>
	        <span class="key col-md-3" value='7'>7</span>
	        <span class="key col-md-3" value='8'>8</span>
	        <span class="key col-md-3" value='9'>9</span>
	        <span class="key clear-key right-key col-md-3" value='C'>C</span>
	        <span class="key col-md-3" value='4'>4</span>
	        <span class="key col-md-3" value='5'>5</span>
	        <span class="key col-md-3" value='6'>6</span>
	        <span class="key right-key col-md-3" value='/'>/</span>
	        <span class="key col-md-3" value='1'>1</span>
	        <span class="key col-md-3" value='2'>2</span>
	        <span class="key col-md-3" value='3'>3</span>
	        <span class="key right-key col-md-3" value='*'>*</span>
	        <span class="key col-md-3" value='0'>0</span>
	        <span class="key col-md-3" value='00'>00</span>
	        <span class="key col-md-3" value='.'>.</span>
	        <span class="key right-key col-md-3" value='+'>+</span>
	        <span class="key equal-key col-md-3" value='='>=</span>
	        <span class="key right-key col-md-3" value='-'>-</span>
	    </div>
	    <!-- money calculator -->
	    <div id="calculator_money" class="col-md-6 col-md-push-3 calculator" style="">
	    	<div id="" class="result"></div>
	        <span class="key key-money col-md-3" value='100'>
	        	<%= image_tag "euroCurrency/100e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='50'>
	        	<%= image_tag "euroCurrency/50e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='20'>
	        	<%= image_tag "euroCurrency/20e", class: " img img-responsive" %>
	      	</span>
	        <span class="key clear-key right-key col-md-3" value='C'>C</span>
	        <span class="key key-money col-md-3" value='10'>
	        	<%= image_tag "euroCurrency/10e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='5'>
	        	<%= image_tag "euroCurrency/5e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='2'>
	        	<%= image_tag "euroCurrency/2e", class: " img img-responsive" %>
	      	</span>
	        <span class="key right-key col-md-3" value='/'>/</span>
	        <span class="key key-money col-md-3" value='1'>
	        	<%= image_tag "euroCurrency/1e", class: " img img-responsive" %>
	        </span>
	         <span class="key key-money col-md-3" value='.50'>
	        	<%= image_tag "euroCurrency/50c", class: " img img-responsive" %>
	        </span>
	        <span class="key key-money col-md-3" value='.20'>
	        	<%= image_tag "euroCurrency/20c", class: " img img-responsive" %>
	        </span>
	        <span class="key right-key col-md-3" value='*'>*</span>
	        <span class="key key-money col-md-3" value='.10'>
	        	<%= image_tag "euroCurrency/10c", class: " img img-responsive" %>
	        </span>
	        <span class="key key-money col-md-3" value='.5'>
	        	<%= image_tag "euroCurrency/5c", class: " img img-responsive" %>
	        </span>
	        <span class="key key-money col-md-3" value='.'>.</span>
	        <span class="key right-key col-md-3" value='+'>+</span>
	        <span class="key equal-key col-md-3" value='='>=</span>
	        <span class="key right-key col-md-3" value='-'>-</span>
	    </div>
	</div>
</div>

<script type="text/javascript">
        $(document).ready(function(){
            var displayValue = '0';   
            $('.result').text(displayValue);
 
            $('.key').each(function(index, key){       
                $(this).click(function(e){
                    if(displayValue == '0') displayValue = '';
                    if($(this).text() == 'C'){
                        displayValue = '0';
                        $('.result').text(displayValue);
                    }
                    else if($(this).text() == '='){
                        try{
                            displayValue = eval(displayValue);
                            $('.result').text(displayValue);
                            displayValue = '0';
                        }
                        catch (e){
                            displayValue = '0';
                            $('.result').text('ERROR');
                        }               
                    }
                    else{
                        displayValue += $(this).attr('value');
                        //alert("adding + " + displayValue);
                        $('.result').text(displayValue);
                    }
                    e.preventDefault()
                })
            })

            $('.numberCalcBtn').click(function(){
            	$('#arrow1').css("visibility", "visible");
            	$('#arrow2').css("visibility", "hidden");
            	$('.calculatorMain').css("background-color", "#78CBC3");
            	$('#calculator_number').toggleClass("hidden");
            	$('#calculator_money').toggleClass("hidden");
            });
            $('.moneyCalcBtn').click(function(){
            	$('#arrow2').css("visibility", "visible");
            	$('#arrow1').css("visibility", "hidden");
            	$('.calculatorMain').css("background-color", "#7b69eb");
            	$('#calculator_money').toggleClass("hidden");
            	$('#calculator_number').toggleClass("hidden");
            });
        })
</script>

app/views/pages/front.html.erb
<%= stylesheet_link_tag "theme" %>
	<section id="home" name="home" style="margin-top: -190px;"></section>
	<div id="headerwrap">
	    <div class="container">
	    	<div class="row centered">
	    		<div class="col-lg-12">
					<h1>Welcome To <b>My Money Counts</b></h1>
					<h3>Helping you to better manage your money</h3>
					<br>
	    		</div>
	    		<div class="col-lg-2">
	    			<h5 id="heroTitle1"><center>Manage your money</center></h5>
	    			<p>Put a budget together in no time using the Drag & Drop budget maker.</p>
	    			<%= image_tag("arrow1", class: "hidden-xs hidden-sm hidden-md") %>
	    		</div>
	    		<div class="col-lg-8">
	    			<%= image_tag("app-bg2", class: "img-responsive mainBg") %>
	    		</div>
	    		<div class="col-lg-2">
	    			<br>
	    			<br>
	    			<br>
	    			<h5>Clearly see where your money goes</h5>
	    			<%= image_tag("arrow2", class: "hidden-xs hidden-sm hidden-md") %>
	    			<!-- <p>Clearly see where your money is going via your dashboard visuals</p> -->
	    			<div style="margin-top: 175px;">
		    			<%= image_tag("plusMore", class: "hidden-xs hidden-sm hidden-md ") %>
		    			<h5 class="andMoreText"> And More!</h5>
	    			</div>
	    		</div>
	    	</div>
	    </div> <!--/ .container -->
	</div><!--/ #headerwrap -->

	<section id="desc" name="desc"></section>
	<!-- INTRO WRAP -->
	<div id="intro">
		<div class="container">
			<div class="row centered">
				<h1>The basics provided by My Money Counts</h1>
				<br>
				<br>
				<div class="col-lg-4">
					<%= image_tag("intro015") %>
					<h3>See where your money goes</h3>
					<p>Visualize your spending habits so you know exactly what's going in, and out.</p>
				</div>
				<div class="col-lg-4">
					<%= image_tag("intro02") %>
					<h3>Get ahead</h3>
					<p>Create budgets for the comming weeks. You can even access old budgets too!</p>
				</div>
				<div class="col-lg-4">
					<%= image_tag("intro032") %>
					<h3>Access Anywhere</h3>
					<p>Use and interact with My Money Counts anywhere using any device.</p>
				</div>
			</div>
			<br>
			<hr>
	    </div> <!--/ .container -->
	</div><!--/ #introwrap -->
	
	<!-- FEATURES WRAP -->
	<div id="features">
		<div class="container">
			<div class="row">
				<h1 class="centered">What can I do with My Money Counts?</h1>
				<br>
				<br>
				<div class="col-lg-6 centered">
					<%= image_tag("mobile", class: "centered", id: "showFeaturesPhone1") %>
					<%= image_tag("mobile2", class: "hidden centered", id: "showFeaturesPhone2") %>
					<%= image_tag("mobile4", class: "hidden centered", id: "showFeaturesPhone4") %>
				</div>
				
				<div class="col-lg-6">
					<h3>Some Features</h3>
					<br>
				<!-- ACCORDION -->
		            <div class="accordion ac" id="accordion2">
		                <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_1 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
		                        Interactive & Effortless Budget Creation
		                        </a>
		                    </div><!-- /accordion-heading -->
		                    <div id="collapseOne" class="accordion-body collapse in">
		                        <div class="accordion-inner">
								<p>A series of tools are availible at the users disposal which ensure a pleasant experience. These tools make Budget creation as simple as it should be. These tools are designed around UX research techniques - and will soon be tested by My Money Counts users to better improve theme.</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>
		
		                <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_2 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
		                        Input Wheel
		                        </a>
		                    </div>
		                    <div id="collapseTwo" class="accordion-body collapse">
		                        <div class="accordion-inner">
								<p>Nobody likes filling out long forms, paper or digital. The process is repetitive and unpleasant - clicking into the field, reading the title and inputting the appropriate answer before continuing to move to the next field. Rinse & Repeat untill the form is completed. This is how it is done on every website & app. <br><br> When answers are required from My Money Counts users, whether it be for creating a Budget or signing up, an interactive wheel can be used. This wheel brings the field to the user each time, no messing, no wasted efferts or time. Cut out the confussion.</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>
		
		                 <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_3 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
		                        Drag & Drop 
		                        </a>
		                    </div>
		                    <div id="collapseThree" class="accordion-body collapse">
		                        <div class="accordion-inner">
								<p>Before a user even fills out a form stating how much they will spend on certain things, first they need to choose what items they will be (rent, going out for dinner, savings etc.) This is another time when the user is prompted for answers. <br> <br> A drag and drop feature is displayed to the user prior to the wheel where they can drag items of their choosing into a box and make a budget depending on these items. Not every budget is the same so having this level of cusomization mixed with its ease of use is a useful solution.</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>
		                
		                 <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_4 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
		                        Visualizations
		                        </a>
		                    </div>
		                    <div id="collapseFour" class="accordion-body collapse">
		                        <div class="accordion-inner">
								<p>When the user creates a budget they can view how their money is being spent using the visual aid(pie chart) provided. This way their spendings can be seen in proportions relative to one another. <br> <br>Its one way to find out you spend nearly as much on junk food as you do rent!</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>			
					</div><!-- Accordion -->
				</div>
			</div>
		</div><!--/ .container -->
	</div><!--/ #features -->
	
	<section id="showcase" name="showcase"></section>
	<div id="showcase">
		<div class="container">
			<div class="row">
				<h1 class="centered">Some Screenshots</h1>
				<br>
				<div class="col-lg-8 col-lg-offset-2">
					<div id="carousel-example-generic" class="carousel slide">
					  <!-- Indicators -->
					  <ol class="carousel-indicators">
					    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
					    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
					  </ol>
					
					  <!-- Wrapper for slides -->
					  <div class="carousel-inner">
					    <div class="item active">
					      <%= image_tag("item-011") %>
					    </div>
					    <div class="item">
					      <%= image_tag("item-022") %>
					    </div>
					    <div class="item">
					      <%= image_tag("item-3") %>
					    </div>
					  </div>
					</div>
				</div>
			</div>
			<br>
			<br>
			<br>	
		</div><!-- /container -->
	</div>	

	<section id="contact" name="contact"></section>
	<div id="footerwrap" style="display: none;">
		<div class="container">
			<div class="col-lg-5">
				<h3>Address</h3>
				<p>
				Av. Greenville 987,<br/>
				New York,<br/>
				90873<br/>
				United States
				</p>
			</div>
			
			<div class="col-lg-7">
				<h3>Drop Us A Line</h3>
				<br>
				<form role="form" action="#" method="post" enctype="plain"> 
				  <div class="form-group">
				    <label for="name1">Your Name</label>
				    <input type="name" name="Name" class="form-control" id="name1" placeholder="Your Name">
				  </div>
				  <div class="form-group">
				    <label for="email1">Email address</label>
				    <input type="email" name="Mail" class="form-control" id="email1" placeholder="Enter email">
				  </div>
				  <div class="form-group">
				  	<label>Your Text</label>
				  	<textarea class="form-control" name="Message" rows="3"></textarea>
				  </div>
				  <br>
				  <button type="submit" class="btn btn-large btn-success">SUBMIT</button>
				</form>
			</div>
		</div>
	</div>
	<div id="c">
		<div class="container">
			<p>Maybe add some Links Here for<a href="http://www.blacktie.co">Budget creation & profile</a></p>
		</div>
	</div>

	<script>
	$('.carousel').carousel({
	  interval: 4000
	})

	$( ".showFeatures_2" ).click(function() {
        //change image with class showFeaturesPhone to mobile2
        $("#showFeaturesPhone1").addClass("hidden");
        $("#showFeaturesPhone2").removeClass("hidden");
    });

    $( ".showFeatures_4" ).click(function() {
        //change image with class showFeaturesPhone to mobile2
        $("#showFeaturesPhone2").addClass("hidden");
        $("#showFeaturesPhone4").removeClass("hidden");
    });
	</script>

app/views/pages/profile.html.erb
<% if !user_signed_in? %>
	You are not Logged in yet. <br><br>
	<%= link_to('Login here', new_user_session_path)  %>  
<% else %>
	 <h1 class="profile_header">Your Profile</h1> 

	
<% end %>

<% @users_budgets.each do |o| %>
	<div style="border: 1px solid black"><%= o.title %></div>
	
<% end  %>
<%= stylesheet_link_tag "profile" %>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-8 col-md-push-2">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <%=image_tag "profile_mmc", class: "img-rounded img-responsive" %>
                    </div>
                    <div class=" col-sm-6 col-md-8">
                        <h4 class="profile_name col-md-8"><%= @user.first_name %> <%= @user.last_name %></h4> 
                        	<%= link_to edit_user_registration_path do %>
                        	  <%= button_tag "Change This", class: "profile_updateBtn btn btn-primary btn-responsive col-md-4" %>
                        	<% end %>
                        	<div class="profileDetails col-md-12">
                        		 <i class="glyphicon glyphicon-globe"></i> Your Email: <text> <%= @user.email %> </text>
	                            <br />
	                            <i class="glyphicon glyphicon-time"></i> You joined 
	                            <text><%= time_ago_in_words(@user.created_at) %></text> ago
	                            <br />
	                            <i class="glyphicon glyphicon-gift"></i> You signed in <text><%= @user.sign_in_count %> </text> times
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
	<div class="row" style="margin-left: 50px;">
        <div class="col-md-4">
            <button class="myBudgetsBtn btn btn-default orange-circle-button" href="">My<br />Budgets<br /></button>
            <div id="myBudgetsContainer">
                <div class="row" id="myBudgetsInfoBox" >
                    <h1 class="purpleFont col-md-8">Your Budgets</h1>
                    <button class="col-md-3 myBudgetsHideBtn">Hide This</button>
                </div> 
                <div class="myBudgets">
                    <% @budgets.each_with_index do |budget, index| %>
                    <h2> <%= link_to "(#{(index + 1)}) " + budget.title, budget_path(budget) %> </h2> <br>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-md-push-4">
            <button class="btn btn-default orange-circle-button" href="">My<br />Games / Modules<br /></button> 
        </div>
	</div>


</div>

<%= javascript_include_tag "profile" %>

app/views/pages/store.html.erb
<!-- some sites for more learning games 
	 http://www.teachingmoney.co.uk/eurosite/euroindex.html 
	 http://www.edtech.ie/details.asp?id=16032&ptid=20124 - too expensive
	 https://www.gynzy.com/teachers/publishers/mathematics/  free
-->
<style>
	.gameDiv{
		background-color: rgba(123, 105, 235, .3);
		text-align: center;
		border-radius: 9px;
		border: 4px solid white;
	}
	.fa-gamepad{
		font-size: 4em;
		color: #7b69eb;
	}
	.ssb-title{ color: black; }
</style>
 <% @iframe_games.each do |iframe_game| %>
     <%= link_to iframe_game do %>
 		<div class="col-md-6 gameDiv">       
			<div class="ssb-icon"><i class="fa fa-gamepad" aria-hidden="true"></i></div>
			<h2 class="ssb-title"><%= iframe_game.title %></h2>       
    	</div>
    <% end %>
<% end %>

   


   



